<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:atom="http://www.w3.org/2005/Atom"
  xmlns:content="http://purl.org/rss/1.0/modules/content/">
<xsl:output method="html" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html>
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title><xsl:value-of select="/rss/channel/title"/> — RSS Feed</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Noto Sans SC', sans-serif;
      background: #0f0f11; color: #e4e4e7;
      max-width: 720px; margin: 0 auto; padding: 2rem 1.5rem;
    }
    h1 { font-size: 1.75rem; font-weight: 700; margin-bottom: 0.25rem; }
    .desc { color: #a1a1aa; font-size: 0.875rem; margin-bottom: 2rem; }
    .item {
      display: block;
      padding: 1rem 0;
      border-bottom: 1px solid #2a2a30;
      text-decoration: none;
      color: inherit;
    }
    .item:last-child { border-bottom: none; }
    .item h2 {
      font-size: 1.1rem; font-weight: 600; margin-bottom: 0.3rem;
      color: #a78bfa;
    }
    .item:hover h2 { text-decoration: underline; }
    .item .meta {
      font-size: 0.8rem; color: #71717a; margin-bottom: 0.4rem;
    }
    .item .summary {
      font-size: 0.9rem; color: #a1a1aa; line-height: 1.5;
    }
    .footer {
      margin-top: 2rem; font-size: 0.8rem; color: #52525b;
      text-align: center;
    }
    .footer a { color: #a78bfa; text-decoration: none; }
    .tag {
      display: inline-block; font-size: 0.7rem; padding: 0.1rem 0.4rem;
      border-radius: 4px; background: rgba(167,139,250,0.1); color: #a78bfa;
      margin-right: 0.3rem; margin-top: 0.3rem; border: 1px solid rgba(167,139,250,0.2);
    }
  </style>
</head>
<body>
  <h1><xsl:value-of select="/rss/channel/title"/></h1>
  <p class="desc"><xsl:value-of select="/rss/channel/description"/></p>
  <p class="desc">
    📡 <xsl:value-of select="count(/rss/channel/item)"/> 篇文章 ·
    <a href="/" style="color:#a78bfa;">返回网站</a>
  </p>

  <xsl:for-each select="/rss/channel/item">
    <a class="item" href="{link}" target="_blank" rel="noopener">
      <h2><xsl:value-of select="title"/></h2>
      <div class="meta">
        <xsl:value-of select="substring(pubDate,1,10)"/>
        <xsl:for-each select="category">
          <span class="tag"><xsl:value-of select="."/></span>
        </xsl:for-each>
      </div>
      <div class="summary"><xsl:value-of select="description"/></div>
    </a>
  </xsl:for-each>

  <div class="footer">
    <a href="/rss.xml">RSS Feed</a> · Generated by MRT Site
  </div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
